name: third_hand_2_0
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  
  
  flutter_signin_button: ^2.0.0
  country_picker: ^2.0.20
 
  
  pinput: ^2.2.31
  


  # Icons
  cupertino_icons: ^1.0.5
  # Splash Screen
  flutter_native_splash: ^2.2.8

  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_app_check: ^0.1.5
  firebase_performance: ^0.9.2+3
  # OTP Field Design
  otp_text_field: ^1.1.3
  # Local Storage
  flutter_secure_storage: ^6.0.0

  # Loction
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.0
  map_launcher: ^2.3.0+1
  # Log In
  google_sign_in: ^5.4.1
  # Email Validate
  email_validator: ^2.1.17
  # Email Opener (Verify Email Case)
  open_mail_app: ^0.4.5
  # Country Picker (Location)
  csc_picker: ^0.2.6
  # Permission Handler (Location, Files)
  permission_handler: 10.0.0
  # Caraousel
  carousel_slider: ^4.1.1
  # State Management
  provider: ^6.0.3
  # Image Packages
  image_picker: ^0.8.5+3
  galleryimage: ^1.2.0
  cached_network_image: ^3.2.1
  # Loader
  legacy_progress_dialog: ^0.1.2
  # Fonts
  google_fonts: ^3.0.1
  # String Formatter
  intl: ^0.17.0
  # Bottom Nav Bar
  dot_navigation_bar: ^1.0.1+4
  # Favourite Button
  like_button: ^2.0.4
  url_launcher: ^6.1.5
  search_page: ^2.0.0+1
  flutter_chat_bubble: ^2.0.0
  custom_pop_up_menu: ^1.2.4
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\images\3rd hand logo.png
    - assets\images\tracking.png
    - assets\images\phone.png
    - assets\images\facebook.png
    - assets\images\google.png
    - assets\images\verify.png
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
